/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Austin Crane (Euclid) (https://sketchfab.com/Euclid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wilson-football-b5677cbb469d4be98e4777c244cfcf27
Title: Wilson Football
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} position={[-9.03, -5.17, -5.17]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
